version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${NAME_APP_DOCKER}
    container_name: ${NAME_APP_DOCKER}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: ${NAME_APP_DOCKER}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${NAME_APP_DOCKER}-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${NAME_APP_DOCKER}-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
     - 8080:80
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
